---
- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ db_packages }}"

- name: Start MySQL service
  ansible.builtin.command:
    cmd: service mysql start

- name: Allow MySQL to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL

- name: Force handler to run now
  ansible.builtin.meta: flush_handlers

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    state: present
